spring:
  app:
    version: 0.0.1
 # config.activate.on-profile: default
  profiles:
    active: default 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.coaq8sw7cq57.us-east-2.rds.amazonaws.com:3306/prueba_spring
    username: admin
    password: Md2e9NEQauobGQdkFGg7
  project:
    name: test
  application:
    name: MS_CUENTA    
  output:
    ansi:
      enabled: always
#  flyway:
#    baseline-on-migrate: true
#    locations:
#      - classpath:db/migration
#      - classpath:db/callback  

server:
  port: 8020
  servlet:
    contextPath: /api/mscuenta
    
   
   

#spring.datasource.driver-class-name: org.postgresql.Driver
#spring.datasource.url: postgresql://creditolistodb-dev.cuzp2cweubda.us-west-1.rds.amazonaws.com:5432/creditoListoDbdev
#spring.datasource.username: root
#spring.datasource.password: root
#spring.datasource.hikari.connectionTimeout: 10000
#spring.datasource.hikari.idleTimeout: 60000 # En el pool de conexiones sólo se puede mantener 60 segundos una conexión inactiva (En producción desactivar)
#spring.datasource.hikari.maxLifetime: 1800000 # Vida últil máxima de una conexión sin uso en el pool será 30 minutos
#spring.datasource.hikari.leakDetectionThreshold: 30000
#spring.datasource.hikari.minimumIdle: 5 # Minima cantidad de conexiones que mantendrá encendidas pero inactivas en el pool  (En producción desactivar)
#spring.datasource.hikari.maximumPoolSize: 11
#spring.datasource.hikari.connection-init-sql: "SET TIME ZONE 'America/Santiago'; SET statement_timeout to 500;"



spring.redis.host: localhost:6379
spring.redis.password: 123
spring.redis.timeout: 350

redis.tiempoexpiracion.cuenta: 2


api.rest.mockend: https://jsonplaceholder.typicode.com/todos/      
   
      
resilience4j.timelimiter:
    configs:
        default:
            cancelRunningFuture: true
            timeoutDuration: 1s
    instances:
        backendA:
            baseConfig: default
        agentTodoObtener:
            timeoutDuration: 500ms
            cancelRunningFuture: true               
            